name: 🚀 New Feature Request
description: Propose a feature for SKKU Alumni backend
title: "🚀 [FEAT] "
labels: ["🚀 Feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: ❓ Problem
      description: 해결하려는 문제를 설명해주세요.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: ✅ Solution
      description: 원하는 결과와 작업 범위를 설명해주세요.
      value: |
        - [ ] task 1
        - [ ] task 2
    validations:
      required: true
  - type: textarea
    id: more
    attributes:
      label: 📍 Additional context
      description: 참고할 자료나 제약사항을 작성해주세요.
  - type: checkboxes
    id: checklist
    attributes:
      label: ✔️ Checklist
      options:
        - label: 관련 이슈가 이미 존재하는지 확인했습니다.
          required: true
