ALTER TABLE users MODIFY COLUMN name VARCHAR(255) NULL;
ALTER TABLE users MODIFY COLUMN category VARCHAR(50) NULL;
ALTER TABLE users MODIFY COLUMN major_id BIGINT NULL;
ALTER TABLE users MODIFY COLUMN admission_year INT NULL;
