ALTER TABLE users ADD COLUMN birth_date_public BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN phone_public BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN email_public BOOLEAN NOT NULL DEFAULT FALSE;

